import type { GlobalState } from "../types";

export const STORAGE_KEYS = {
  tabs: "markdownViewerTabs",
  activeTab: "markdownViewerActiveTab",
  untitledCounter: "markdownViewerUntitledCounter",
  global: "markdownViewerGlobalState",
  language: "app-lang",
  findDocked: "find-replace-docked",
};

export const MAX_TABS = 20;
export const MAX_IMPORT_BYTES = 10 * 1024 * 1024;
export const SHARE_URL_SOFT_LIMIT = 32_000;

export const DEFAULT_GLOBAL_STATE: GlobalState = {
  theme: "light",
  viewMode: "split",
  syncScroll: true,
  splitPercent: 50,
  language: "en",
  direction: "ltr",
  offlineFirst: true,
  findDocked: false,
};

export const LANGUAGE_LABELS: Record<string, string> = {
  en: "English",
  zh: "简体中文",
  tw: "繁體中文",
  ja: "日本語",
  ko: "한국어",
  pt: "Português",
  es: "Español",
  fr: "Français",
  de: "Deutsch",
  ru: "Русский",
  it: "Italiano",
  tr: "Türkçe",
  pl: "Polski",
  uk: "Українська",
};

export const UI_TEXT: Record<string, Record<string, string>> = {
  en: {
    import: "Import",
    export: "Export",
    share: "Share",
    copy: "Copy",
    newTab: "New",
    reset: "Reset",
    editor: "Editor",
    split: "Split",
    preview: "Preview",
    sync: "Sync",
    offline: "Offline first",
    find: "Find",
    replace: "Replace",
    all: "All",
    current: "Current",
    markdown: "Markdown",
    html: "HTML",
    pdf: "PDF",
    png: "PNG",
  },
  zh: {
    import: "导入",
    export: "导出",
    share: "分享",
    copy: "复制",
    newTab: "新建",
    reset: "重置",
    editor: "编辑",
    split: "分屏",
    preview: "预览",
    sync: "同步",
    offline: "离线优先",
    find: "查找",
    replace: "替换",
    all: "全部",
    current: "当前",
    markdown: "Markdown",
    html: "HTML",
    pdf: "PDF",
    png: "PNG",
  },
  tw: {
    import: "匯入",
    export: "匯出",
    share: "分享",
    copy: "複製",
    newTab: "新增",
    reset: "重置",
    editor: "編輯",
    split: "分割",
    preview: "預覽",
    sync: "同步",
    offline: "離線優先",
    find: "尋找",
    replace: "取代",
    all: "全部",
    current: "目前",
    markdown: "Markdown",
    html: "HTML",
    pdf: "PDF",
    png: "PNG",
  },
};

export const DIAGRAM_LANGUAGES = new Set([
  "mermaid",
  "abc",
  "geojson",
  "topojson",
  "stl",
  "plantuml",
  "d2",
  "graphviz",
  "dot",
  "vega-lite",
  "vegalite",
  "wavedrom",
  "markmap",
]);
